### ISSUE TITLE
middle name

### ISSUE THREAD

**Issue by bishesh** [bishesh/Science-innovation-Nepal#16]
@biwek The current form has only First name and last name fields. Can we have a field for an optional middle name ?

**Comment by biwek** [comment]
@bishesh first name field was meant for both first and middle names. Also less fields were done for clarity and for easier searchability. Maybe we could rename the label for that field to be more clear.

**Comment by bishesh** [comment]
Ah all right. Yes, renaming First name to "First and Middle Names" and not adding more fields then ? thanks.
