### ISSUE TITLE
Add more disciplines

### ISSUE THREAD

**Issue by bishesh** [bishesh/Science-innovation-Nepal#18]
@biwek Food techhnology and engineering needs to be added as other existing disciplines don't seem to really represent this field. E.g. [here](https://scholar.google.co.uk/citations?user=LVco9msAAAAJ&hl=en&oi=ao)

**Comment by bishesh** [comment]
Can we rename the discipline "Economics" with "Economics, Trade, Finance and Business" ?

Subdisciplines:

1. MicroEconomics 
2. MacroEconomics
3. International Trade
4. International Money and Finance
5. Business Management

**Comment by biwek** [comment]
@bishesh would "Food techhnology and engineering" be a discipline itself or a sub-discipline?

**Comment by bishesh** [comment]
@biwek It can be a discipline in itself, but if we cannot select discipline and must select a sub-discipline, then perhaps it can be kept as both discipline and sub-discipline (under itself).

**Comment by biwek** [comment]
addressed in https://github.com/AbhinavNepal/abhinav-nepal/commit/cbd5e742857aabac457c857304a5cb80639be73b.
