### ISSUE TITLE
add new positions

### ISSUE THREAD

**Issue by bishesh** [bishesh/Science-innovation-Nepal#19]
@biwek : Many people work in research institutes where they have positions such as Research Scientist, Senior Research Scientist, Director of Research. One example [here](https://scholar.google.com/citations?user=b1qGAhgAAAAJ&hl=en). 
Can we add the following please ?
1. Research Scientitst
2. Senior Research Scientist
3. Research Scientist Director

**Comment by bishesh** [comment]
@biwek  Also need to add:
4. Senior Lecturer

**Comment by biwek** [comment]
addressed in https://github.com/AbhinavNepal/abhinav-nepal/commit/cbd5e742857aabac457c857304a5cb80639be73b.
