### ISSUE TITLE
Transfering the repo from personal account to a community

### ISSUE THREAD

**Issue by bishesh** [bishesh/Science-innovation-Nepal#2]
As of now, this repository is hosted under my personal account.
Raunak Shrestha, in facebook, proposed the following:

" Really appreciate the move and a good resource. Seems like its currently under your personal github a/c. Perhaps if we can host the resource under some other github a/c and assign admin role to few other people in the community then we can make it much more comprehensive. I'm willing to contribute more to this. Please let us know. :D " 

I think this is a good idea. To keep the history of the discussion attached with the repo, I have created this issue here instead of discussing it on facebook.

**Comment by bishesh** [comment]
That's a good idea Raunak.
It would be nice to move this repo to another account with few admins from the (about to be built :) ) community. 

So what kind of github account do you suggest ? An "organization account" where there are few admins with few owners and administrators, or just another personal github account with a suitable name and shared password amongst the admins ? I think the first option is better.

We also need to first agree on basic guidelines for the repository and the resources.
These guidelines should help us answer following questions that can come in the future:
1. Who will be allowed to be admins and how many ?
2. How do we decide on the names of the people and organizations to be added ?
3. What are the main objectives of these resources ?

...

So let us find out a set of basic guidelines that we can agree upon and then we can create an account with admin access for all of us.

**Comment by bishesh** [comment]
Here are my thoughts; I am also looking forward to hear thoughts from others.

**Copyright and usage:** 
All the information we put in should be collected from public websites such as google scholar, researchgate, personal/academic websites of the related people. All of our content should always be open access and freely available. The collective information produced as a result of the resources in this website, and any new information/data that use these resources should always be open access and freely available.

**Admins** 
- Should share the common vision of building these resources with the sole objective of contributing towards the development of science, technology and innovation in Nepal.
- Should reasonably contribute in expanding this resource and also improving its quality.

**Adding names of people**
- How do we decide whether we add someone here or not ? To the least, their list of publications should be be publicly available and they must be actively engaged in research. 
I think we should add only currently active researchers who work on research problems and publish articles in reputed conferences and journals of their respected fields.
Having a PhD should be neither a necessary nor a sufficient condition for making into the list. The person must be active, contributing to the research community, and society by regularly publishing papers. Thus, someone who is working in an industry but regularly publishes scientific articles related to their work will also be enlisted.
We could include PhD candidates too, if they are publishing articles in the most reputed international journals/conferences of their respective fields. But this needs help from people who actually know their field and can make a fair judgment on what qualifies as good quality publications in their respective fields.  

**Adding names of research institutes**
The organizations must regularly update their list of contributions in peer-reviewed conferences and journals of "good quality".
Reports written by NGOs without any corresponding publications in a peer-review journals/conferences should not count!

**Comment by raunakms** [comment]
Yes, we must discuss these issues and have a clear idea first. Until then we can continue to populate the current repository. I could pull my own personal strings to get hold more content that we have already compiled. I will keep you updated.

**Comment by bishesh** [comment]
Sounds good, thanks.

**Comment by bishesh** [comment]
@raunakms @bamsumit : I have transferred this repo from my personal account to organizational account with a name AbhinavNepal (अभिनव => innovative, young). 
I still need to add some basic guildelines, todo lists and long term visions, but would be happy to discuss these with you and also get contributions. 
In the mean time contributions for documentation, new materials would be great.
Thanks
