### ISSUE TITLE
field economics

### ISSUE THREAD

**Issue by bishesh** [bishesh/Science-innovation-Nepal#20]
@biwek I tried to add Parag Pathak who is under economics [here](https://abhinavnepal.github.io/Science-innovation-Nepal/Nepali-scholars/). But we don't have Economics field in the drop-down list.

**Comment by bishesh** [comment]
Same with education, trying to add Bal Chandra Luitel under education [here](https://abhinavnepal.github.io/Science-innovation-Nepal/Nepali-scholars/)

**Comment by biwek** [comment]
I may have missed those @bishesh. Could you add these missing disciplines to the issue you had [previously created](https://github.com/AbhinavNepal/Science-innovation-Nepal/issues/18).

If you could also mention which parent discipline the specified sub-discipline should fall under would be great.

**Comment by biwek** [comment]
"Mathematics" sub-discipline should already be there under parent "Education" discipline. Are you sure you cannot see it in the dropdown?

**Comment by bishesh** [comment]
Ah, yes Mathematics is present under Education. For the others I'll add them in the previously created issue you linked. Thanks.
