### ISSUE TITLE
Nepali research institutes doing great works in the field of your interest 

### ISSUE THREAD

**Issue by AnuragAdhikari** [bishesh/Science-innovation-Nepal#3]
Research Institute: **Kathmandu Research Institute for Biological Sciences** (KRIBS)
Location: Mahalaxmi-19, Lalitpur, Nepal
Research Focus: Infection & Immunology, Natural Products
Introduction: Kathmandu Research Institute for Biological Sciences (KRIBS) is a non-governmental, non-political and non-profit making institute established in 2017. We are a team of scientist and technicians focused on research and development of tools and techniques with an aim to enable the study inside biological sciences. The research at KRIBS particularly aims to decipher complex questions prevailed around us, among us; so as to find potential and possible answers, which could solve or at least illuminate the problem we are facing. It is registered in District Administration Office, Lalitpur, Nepal with registration no. 4512/073 and Social Welfare Council Nepal with affiliation no. 45260. 
Website: http://kribs.org.np/

**Comment by bishesh** [comment]
Done! Thanks!
