### ISSUE TITLE
Addition request for the addition on "Nepali Scholars"

### ISSUE THREAD

**Issue by AnuragAdhikari** [bishesh/Science-innovation-Nepal#4]
Anurag Adhikari (Infectious Disease)
- Department of Infection and Immunology, Kathmandu Research Institute for Biological Sciences.
- Understanding host pathogen interaction with specific focus on immune activation.

https://scholar.google.com/citations?user=fCMN91IAAAAJ&hl=en
https://www.researchgate.net/profile/Anurag_Adhikari

**Comment by bishesh** [comment]
Done!
