### ISSUE TITLE
Nepali Scholar working in Nepal

### ISSUE THREAD

**Issue by AnuragAdhikari** [bishesh/Science-innovation-Nepal#5]
Birendra Prasad Gupta (http://kribs.org.np/advisory-members/)
Virology Unit, Central Department of Biotechnology, Tribhuvan University, Nepal
Expertise: Virology 
https://www.researchgate.net/profile/Birendra_Gupta2/publications

**Comment by raunakms** [comment]
@bishesh : Did you see my commits? I have added about 13 records to the list. Perhaps it needs your approval.

**Comment by bishesh** [comment]
@raunakms I hadn't because I had not received any notifications. You have to make a pull request for me to get notified, and then I will also be able to merge your commits (https://help.github.com/articles/creating-a-pull-request-from-a-fork/).

**Comment by raunakms** [comment]
@bishesh thanks I believe I did it now

**Comment by bishesh** [comment]
@AnuragAdhikari [Done](https://bishesh.github.io/Science-innovation-Nepal/Nepali-scholars/#sec-1-3)
